export { default as Predate } from './BelumBuka';
export { default as NotifSukses } from './Lolos';
export { default as Tutup } from './Tutup';
export { default as Terdaftar } from './Terdaftar';
export { HomeHeader } from './HomeHeader';
export { KontenSatu } from './KontenSatu';
export { KontenDua } from './KontenDua';
export { KontenTiga } from './KontenTiga';
export { default as PengantarKiri } from './Pengantar1';
export { default as PengantarKanan } from './Pengantar2';
